version: "3"
services:
  api:
    image: zeff-mail
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: zeff-mail
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
